#########################################################################
# Title:            Coolflix: Grafana                                   #
# Author(s):        Fma965                                              #
# URL:              https://github.com/Fma965/Cloudbox                  #
# Docker Image(s):  grafana/grafana                                     #
# --                                                                    #
#   (Modified) Part of the Cloudbox project: https://cloudbox.works     #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: grafana
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: grafana
    state: absent

- name: Create opt directory
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "472"
    group: "472"
    recurse: yes
  with_items:
    - /opt/grafana

- name: Create and start container
  docker_container:
    name: grafana
    image: "grafana/grafana:latest"
    pull: yes
    published_ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/grafana:/var/lib/grafana"
      - "/opt/grafana/grafana.ini:/etc/grafana/custom.ini"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ user.pass }}"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-worldmap-panel"
      GF_SERVER_ROOT_URL: "https://grafana.{{ user.domain }}"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.grafana.tls": "true"
    networks:
      - name: cloudbox
        aliases:
          - grafana
    purge_networks: yes
    restart_policy: unless-stopped
    state: started