---
- hosts: localhost
  vars_files:
    - ['accounts.yml', 'defaults/accounts.yml.default']
    - ['settings.yml', 'defaults/settings.yml.default']
    - ['adv_settings.yml', 'defaults/adv_settings.yml.default']
    - ['backup_config.yml', 'defaults/backup_config.yml.default']
  roles:
    - { role: sanity_check, tags: ['sanity_check'] }
    - { role: settings, tags: ['always', 'settings'] }
    - { role: pre_tasks, tags: ['pre_tasks'] }
    - { role: backup, tags: ['backup'] }
    - { role: restore, tags: ['restore'] }
    - { role: kernel, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'preinstall', 'kernel'] }
    - { role: user, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'preinstall', 'user'] }
    - { role: shell, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'preinstall', 'shell'] }
    - { role: rclone, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'preinstall', 'rclone'] }
    - { role: system, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'system'] }
    - { role: common, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'common'] }
    - { role: aliases, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'aliases'] }
    - { role: motd, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'motd'] }
    - { role: docker, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'docker'] }
    - { role: remote, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'mounts', 'mounts_override'], when: ['use_remote'] }
    - { role: unionfs, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'mounts', 'mounts_override'] }
    - { role: scripts, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'scripts'] }
    - { role: traefik, tags: ['core', 'cloudbox', 'mediabox', 'feederbox', 'traefik'] }
    - { role: plex, tags: ['cloudbox', 'mediabox', 'plex'] }
    - { role: plexpy, tags: ['cloudbox', 'mediabox', 'plexpy'] }
    - { role: ombi, tags: ['cloudbox', 'mediabox', 'ombi'] }
    - { role: plex_autoscan, tags: ['cloudbox', 'mediabox', 'plex_autoscan'] }
    - { role: portainer, tags: ['cloudbox', 'feederbox', 'portainer'] }
    - { role: organizr, tags: ['cloudbox', 'feederbox', 'organizr'] }
    - { role: cloudplow, tags: ['cloudbox', 'feederbox', 'cloudplow'], when: ['use_remote'] }
    - { role: nzbget, tags: ['cloudbox', 'feederbox', 'nzbget'], when: ['use_nzbs'] }
    - { role: jackett, tags: ['cloudbox', 'feederbox', 'jackett'], when: ['use_torrents'] }
    - { role: nzbhydra2, tags: ['cloudbox', 'feederbox', 'nzbhydra2'], when: ['use_nzbs'] }
    - { role: sonarr, tags: ['cloudbox', 'feederbox', 'sonarr'] }
    - { role: radarr, tags: ['cloudbox', 'feederbox', 'radarr'] }
    - { role: lidarr, tags: ['cloudbox', 'feederbox', 'lidarr'] }
    - { role: plex_auth_token, tags: ['plex_auth_token'] }
    - { role: trakttv-plugin, tags: ['trakttv-plugin'] }
    - { role: watchtower, tags: ['watchtower'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: mariadb, tags: ['mariadb'] }
    - { role: traktarr, tags: ['traktarr'] }
    - { role: plex_dupefinder, tags: ['plex_dupefinder'] }
    - { role: netdata, tags: ['netdata'] }
    - { role: plex_patrol, tags: ['plex_patrol'] }
    - { role: nowshowing, tags: ['nowshowing'] }
    - { role: bazarr, tags: ['bazarr'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: nzbthrottle, tags: ['nzbthrottle'] }
    - { role: community, tags: ['community'] }
    # --- Custom roles added by Fma965 for Coolflix ---
    - { role: plex-ldap, tags: ['plex-ldap'] }
    - { role: jdownloader2, tags: ['jdownloader2'] }
    - { role: synclounge, tags: ['synclounge'] }
    - { role: handbrake, tags: ['handbrake'] }
    - { role: grafana, tags: ['grafana'] }
    - { role: influxdb, tags: ['influxdb'] }
    - { role: varken, tags: ['varken'] }
    - { role: telegraf, tags: ['telegraf'] }
    - { role: mellow, tags: ['mellow'] }
    - { role: monitorr, tags: ['monitorr'] }
    - { role: qbittorrentvpn, tags: ['qbittorrentvpn'] }