#########################################################################
# Title:         Cloudbox: Netdata Role                                 #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# Docker Image:  titpetric/netdata                                      #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: netdata
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: netdata
    state: absent

- name: Create and start container
  docker_container:
    name: netdata
    image: "titpetric/netdata:latest"
    pull: yes
    capabilities:
      - SYS_PTRACE
    published_ports:
      - "127.0.0.1:19999:19999"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.netdata.tls": "true"
      "traefik.http.routers.netdata.tls": "oauth-coadmin@file"
    networks:
      - name: cloudbox
        aliases:
          - netdata
    purge_networks: yes
    restart_policy: unless-stopped
    security_opts:
      - apparmor:unconfined
    state: started
