#########################################################################
# Title:            Community: Mellow                                   #
# Author(s):        Superduper09                                        #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  voidp/mellow                                        #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: mellow
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: mellow
    state: absent

- name: Create mellow directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /opt/mellow

- name: Create and start container
  docker_container:
    name: mellow
    image: voidp/mellow
    pull: yes
    published_ports:
      - "127.0.0.1:5060:5060"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
    volumes:
      - "/opt/mellow:/usr/src/app/data/"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.mellow.tls": "true"
    networks:
      - name: cloudbox
        aliases:
          - mellow
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
