#########################################################################
# Title:            Community: Handbrake                                #
# Author(s):        Satz                                                #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  jlesage/handbrake                                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: handbrake
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: handbrake
    state: absent

- name: Create handbrake directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /opt/handbrake

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Create and start container
  docker_container:
    name: handbrake
    image: jlesage/handbrake
    pull: yes
    published_ports:
      - "127.0.0.1:6900:5800"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      CLEAN_TMP_DIR: "1"
      ENABLE_CJK_FONT: "1"
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
    volumes:
      - "/opt/handbrake:/config:rw"
      - "/mnt:/storage:ro"
      - "/mnt/local/downloads/handbrake/watch:/watch:rw"
      - "/mnt/local/downloads/handbrake/output:/output:rw"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and dev_dri.stat.exists) | default(false) else omit }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.handbrake.tls": "true"
      "traefik.http.routers.handbrake.middlewares": "oauth-coadmin@file"
    networks:
      - name: cloudbox
        aliases:
          - handbrake
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
