#########################################################################
# Title:         Sanity Check - Logs Check                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Get 'coolflix.yml' info
  stat:
    path: "{{ playbook_dir }}/coolflix.yml"
  register: coolflix_yml

- name: Touch 'cloudbox.log' file
  file:
    path: "{{ playbook_dir }}/cloudbox.log"
    state: touch
    owner: "{{ coolflix_yml.stat.uid }}"
    group: "{{ coolflix_yml.stat.gid }}"
    mode: 0664
