#########################################################################
# Title:            Cloudbox: Nextcloud Role                            #
# Author(s):        l3uddz, desimaniac                                  #
# URL:              https://github.com/cloudbox/cloudbox                #
# Docker Image(s):  linuxserver/nextcloud                               #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: MariaDB Role
  include_role:
    name: mariadb

- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: nextcloud
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - nextcloud

- name: Create required directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /opt/nextcloud
    - /opt/nextcloud/conf
    - /opt/nextcloud/data

- name: Create and start nextcloud container
  docker_container:
    name: nextcloud
    image: "linuxserver/nextcloud"
    pull: yes
    published_ports:
      - "127.0.0.1:4645:443"
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      VIRTUAL_HOST: "nextcloud.{{ user.domain }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/nextcloud/conf:/config"
      - "/opt/nextcloud/data:/data"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.nextcloud.tls": "true"
      "traefik.http.services.nextcloud.loadbalancer.server.port": "443"
      "traefik.http.services.nextcloud.loadbalancer.server.scheme": "https"
      "traefik.http.routers.nextcloud.rule": "Host(`cloud.{{ user.domain }}`)"
    networks:
      - name: cloudbox
        aliases:
          - nextcloud
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
