<?php
	require '/config/www/config.php';
	$plex = mysqli_real_escape_string($con,$_GET['u']);
	$query = "SELECT name FROM users WHERE plex LIKE '$plex' LIMIT 1;";
	$result = mysqli_query($con, $query);
	$name = '';
if (mysqli_num_rows($result) > 0) {
    // output data of each row
    while($row = mysqli_fetch_assoc($result)) {
        $name =  $row["name"];
    }
} else {
    die('Direct access not allowed');
}
?>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Coolflix Pricing</title>
		<link href="//bootswatch.com/4/slate/bootstrap.min.css" rel="stylesheet"/>
		<style>		
.container-fluid {	margin: auto; max-width: 1800px;}
.row { margin: 50px 0; }
.flex {
    display: flex;
    flex-wrap: wrap;
    flex-direction: row;
    align-items: center;
    background: transparent;
    box-shadow: none !important;
    transition: all .4s ease-in-out;
    cursor: pointer
}

img {
    vertical-align: middle;
    border-style: none;
    width: calc(100%);
    max-width: 400px;
    margin-top: 20px;
    margin-bottom: -20px;
}

.flex-child { padding: 3px; flex-grow: 1; flex-basis: 0;}
#grafanadwidget { position: relative; height: calc(80px); width: calc(100%);}
@media only screen and (max-width: 650px) {.flex-child-big {flex-basis: auto;min-width: auto !important;} }
@media only screen and (max-width: 1125px) {.flex-child-big {flex-basis: auto;min-width: 600px;flex-basis: fit-content;}}
@media only screen and (max-width: 1649px) {.flex-child {flex-basis: auto;}}
		</style>
	</head>
		<body role="document">
		<center><img src="https://i.imgur.com/j9SFsKv.png"/></center>
	<div class="container-fluid theme-showcase" role="main"> 
<div class="row">
	<!-- Plans -->
	<div class='well col-lg-12'>
		<h2>Available Plans - Page generated by <span style="color:cyan"><?=$name?></span><br /></h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Plan</th>
						<th>Cost</th>
						<th>Details</th>
					</tr>
				</thead>
				<tbody>
				<?php
				$query = mysqli_real_escape_string($con,"SELECT * FROM plans;");
				$sqltran = mysqli_query($con, $query)or die(mysqli_error($con));
				
				while ($row = mysqli_fetch_array($sqltran)) {	
				?>
					<tr class="active-<?=$row['enabled']?>">
						<td><?=$row['plan']?></td>
						<td>£<?=number_format(round($row['cost'], 2),2)?></td>
						<td><?=nl2br($row['details'])?></td>
					</tr>
				<?php }	?>
				</tbody>
			</table>
	</div>
</div>
<div class="row">
	<!-- Plans -->
	<div class='well col-lg-12'>
		<h2>Current Statistics</h2>
<!-- -------------------SMALL WIDGET START------------------- -->
    <div class="content-box flex">
    <!-- -------------------WIDGET------------------- -->
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider">
    <iframe class="iframe" id="grafanadwidget" 
    frameborder="0" src="https://grafana.coolflix.stream/d-solo/bj0JnBMmz/varken-dashboard-for-organizr-homepage?orgId=1&refresh=5m&var-datasource=varken&var-movielibrary=Movies&var-tvlibrary=TV%20Shows&panelId=49"></iframe>
    </div></div>
    <!-- -------------------WIDGET------------------- --> 
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider">
    <iframe class="iframe" id="grafanadwidget" 
    frameborder="0" src="https://grafana.coolflix.stream/d-solo/bj0JnBMmz/varken-dashboard-for-organizr-homepage?orgId=1&refresh=5m&var-datasource=varken&var-movielibrary=Movies&var-tvlibrary=TV%20Shows&panelId=51"></iframe>
    </div></div>
    <!-- -------------------WIDGET------------------- -->     
    <div class="flex-child" id="flex-grafanadwidget">
    <div class="overflowhider">
    <iframe class="iframe" id="grafanadwidget" 
    frameborder="0" src="https://grafana.coolflix.stream/d-solo/bj0JnBMmz/varken-dashboard-for-organizr-homepage?orgId=1&refresh=5m&panelId=82"></iframe>
    </div></div>
</div>
	</div>
</div>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
	</body>
</html>