#########################################################################
# Title:         Cloudbox: Pre-Tasks                                    #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Set User Variables
  import_tasks: "subtasks/user.yml"
  tags: always

- name: Clean Paths
  import_tasks: "subtasks/clean_paths.yml"
  tags: always

- name: Set Cloudbox Variables
  import_tasks: "subtasks/variables.yml"
  tags: always

- name: Set Cloudbox Role Variables
  import_tasks: "subtasks/role_variables.yml"
  tags: always

- name: APT Tasks
  import_tasks: "subtasks/apt.yml"
  tags: always

- name: Sub Domain Tasks
  block:

  - name: "Set Cloudbox Type to 'cloudbox'"
    set_fact:
      cloudbox_type: "cloudbox"
    tags: cloudbox

  when: (cloudflare_enabled) and ('pre_tasks' not in ansible_run_tags)
