#########################################################################
# Title:            Community: JDownloader2                             #
# Author(s):        Fma965, maximuskowalski, desimaniac                 #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  jlesage/jdownloader-2                               #
#                   rix1337/docker-myjd-api                             #
# --                                                                    #
#   (Modified) Part of the Cloudbox project: https://cloudbox.works     #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: jdownloader2
    state: absent

- name: Stop and remove any existing container
  docker_container:
    name: jdownloader2-api
    state: absent

- name: Create jdownloader2 directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /opt/jdownloader2
    - /opt/jdownloader2/config
    - /opt/jdownloader2/config/libs
    - /mnt/local/downloads/jdownloader2/output
    - /opt/myjdownloaderapi

- name: Import 7zip 1509
  copy:
    src: "sevenzipjbinding1509.jar"
    dest: "/opt/jdownloader2/config/libs/sevenzipjbinding1509.jar"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no

- name: Import 7zip 1509Linux
  copy:
    src: "sevenzipjbinding1509Linux.jar"
    dest: "/opt/jdownloader2/config/libs/sevenzipjbinding1509Linux.jar"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: no

- name: Create and start container
  docker_container:
    name: jdownloader2
    image: "jlesage/jdownloader-2:latest"
    pull: yes
    published_ports:
      - "127.0.0.1:5800:5800"
      - "127.0.0.1:5900:5900"
    env:
      TZ: "{{ tz }}"
      DISPLAY_WIDTH: "1920"
      DISPLAY_HEIGHT: "1080"
      VNC_PASSWORD: "{{ user.pass }}"
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      CLEAN_TMP_DIR: "1"
      UMASK: "000"
    volumes:
      - "/mnt/local/downloads/jdownloader2/output:/output:rw"
      - "/mnt:/mnt:rw"
      - "/opt/jdownloader2/config:/config:rw"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.jdownloader2.tls": "true"
      "traefik.http.services.jdownloader2.loadbalancer.server.port": "5800"
      "traefik.http.routers.jdownloader2.rule": "Host(`downloads.{{ user.domain }}`)"
      "traefik.http.routers.jdownloader2.middlewares": "oauth-poweruser@file"
    networks:
      - name: cloudbox
        aliases:
          - jdownloader2
    purge_networks: yes
    restart_policy: unless-stopped
    state: started

- name: Create and start container
  docker_container:
    name: jdownloader2-api
    image: "rix1337/docker-myjd-api:latest"
    pull: yes
    published_ports:
      - "127.0.0.1:8478:8080"
    env:
      USER: "{{ user.email }}"
      PASS: "{{ user.pass }}"
    volumes:
      - "/opt/myjdownloaderapi:/config:rw"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.enable": "false"
    networks:
      - name: cloudbox
        aliases:
          - jdownloader2-api
    purge_networks: yes
    restart_policy: unless-stopped
    state: started