#########################################################################
# Title:            Cloudbox: Radarr4K Role                             #
# Author(s):        l3uddz, desimaniac                                  #
# URL:              https://github.com/cloudbox/cloudbox                #
# Docker Image(s):  hotio/radarr,                                       #
#                   andrewkhunn/suitarr_mp4_automator                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: radarr4k
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: radarr4k
    state: absent

- name: Create radarr4k directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - /opt/radarr4k

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Set 'default_volumes' variable
  set_fact:
    default_volumes:
      - "/opt/radarr4k:/config"
      - "/opt/scripts:/scripts"
      - "/mnt:/mnt"
      - "/mnt/unionfs/Media/4K Movies:/movies"

- name: Create and start container
  docker_container:
    name: radarr4k
    image: "hotio/radarr"
    pull: yes
    published_ports:
      - "127.0.0.1:7879:7879"
    env:
      BACKUP: "no"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      UMASK: 002
      TZ: "{{ tz }}"
    volumes: "{{ default_volumes + nzbs_downloads_path|default([]) + torrents_downloads_path|default([]) }}"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and sickbeard_mp4_automator and dev_dri.stat.exists) | default(false) else omit }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.radarr4k.tls": "true"
      "traefik.http.routers.radarr4k.middlewares": "oauth-poweruser@file"
    networks:
      - name: cloudbox
        aliases:
          - radarr4k
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
