#########################################################################
# Title:         Cloudbox: Plex Role                                    #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Set DNS Record on CloudFlare"
  include_role:
    name: cloudflare-dns
  vars:
    subdomain: "plex"
  when: cloudflare_enabled

- name: "Create Plex directories"
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    recurse: yes
  with_items:
    - "/opt/plex"
    - "/opt/plex/Library"
    - "/opt/plex/Library/Application Support"
    - "/opt/plex/Library/Application Support/Plex Media Server"
    - "/opt/plex/Library/Application Support/Plex Media Server/Plug-ins"
    - "/opt/plex/Library/Logs"
    - "/opt/plex/Library/Logs/Plex Media Server"
    - "{{ plex.transcodes }}/plex"

- name: "Stop and remove any existing container"
  docker_container:
    name: plex
    state: absent

- name: "Check if '/dev/dri' exists"
  stat:
    path: "/dev/dri"
  register: dev_dri

- name: Preferences Tasks
  import_tasks: "subtasks/preferences/preferences.yml"
  when: (not continuous_integration)

- name: "Create and start container"
  docker_container:
    name: plex
    image: "cloudb0x/plex:{{ plex.tag }}"
    pull: yes
    published_ports:
      - "127.0.0.1:32400:32400/tcp"
      - "127.0.0.1:3005:3005/tcp"
      - "127.0.0.1:8324:8324/tcp"
      - "127.0.0.1:32469:32469/tcp"
      - "127.0.0.1:1900:1900/udp"
      - "127.0.0.1:32410:32410/udp"
      - "127.0.0.1:32412:32412/udp"
      - "127.0.0.1:32413:32413/udp"
      - "127.0.0.1:32414:32414/udp"
    env:
      PLEX_UID: "{{ uid }}"
      PLEX_GID: "{{ gid }}"
      PLEX_CLAIM: "{{ (plex_claim_code) | default(omit) }}"
      CHANGE_CONFIG_DIR_OWNERSHIP: false
      ADVERTISE_IP: "http://plex.{{ user.domain }}:80/,https://plex.{{ user.domain }}:443/"
      HEALTHCHECK_MOUNT: /mnt/unionfs
      NVIDIA_DRIVER_CAPABILITIES: "{{ 'compute,video,utility' if (gpu.nvidia.enabled) | default(false) else omit }}"
      NVIDIA_VISIBLE_DEVICES: "{{ 'all' if (gpu.nvidia.enabled) | default(false) else omit }}"
      TZ: "{{ tz }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/plex:/config"
      - "/opt/scripts:/scripts"
      - "/mnt/unionfs/Media:/data"
      - "/mnt:/mnt"
      - "/tmp:/tmp"
      - "/dev/shm:/dev/shm"
      - "{{ plex.transcodes }}/plex:/transcode"
    devices: "{{ '/dev/dri:/dev/dri' if (gpu.intel and dev_dri.stat.exists) | default(false) else omit }}"
    etc_hosts:
      "metric.plex.tv": "127.0.0.1"
      "metrics.plex.tv": "127.0.0.1"
      "analytics.plex.tv": "127.0.0.1"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
      "traefik.http.routers.plex.tls": "true"
      "traefik.http.services.plex.loadbalancer.server.port": "32400"
    networks:
      - name: cloudbox
        aliases:
          - plex
    purge_networks: yes
    restart_policy: unless-stopped
    state: started

# Sometimes docker will set transcodes folder to root after a restore.
- name: "Ensure transcodes folder has the correct permissions"
  file:
    path: "{{ plex.transcodes }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    recurse: yes

- name: Extra Tasks
  import_tasks: "subtasks/extra.yml"
  ignore_errors: yes
  tags: plex-extra-tasks
